### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by omanhom** [orbs-network/ton-gateway#39]
**why in testnet post url:https://ton.access.orbs.network/4411c0ff5Bd3F8B62C092Ab4D238bEE463E64411/1/testnet/ton-api-v4/send**
Error: Request failed with status code 500
at createError (/Volumes/slave3/ton/flappy-bird/node_modules/@ton/ton/node_modules/axios/lib/core/createError.js:16:15)
at settle (/Volumes/slave3/ton/flappy-bird/node_modules/@ton/ton/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/Volumes/slave3/ton/flappy-bird/node_modules/@ton/ton/node_modules/axios/lib/adapters/http.js:313:11)
at IncomingMessage.emit (node:events:531:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
[ERROR] 16:19:20 Error: Request failed with status code 500

**Comment by benedya** [comment]
hi @omanhom 

For me it worked when I stopped using `getHttpEndpoint` but create `TonClient` with already known endpoint.

So, instead of:
```
import { getHttpEndpoint } from '@orbs-network/ton-access';

const endpoint = await getHttpEndpoint({
    network: 'mainnet',
  });

const client = new TonClient({ endpoint })
```

I started using:
```
const endpoint = 'https://toncenter.com/api/v2/jsonRPC';
const client = new TonClient({ endpoint })
```

More examples you can find here https://www.npmjs.com/package/@ton/ton
